


GET http://localhost:3000/users.json
Content-Type: application/json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "user 2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}

### Users show
GET http://localhost:3000/users/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNTc0NTN9.TMQY5EZPnjKn0q5k2RfEoinvYhQFylxBl-1FeSw6ALs
Content-Type: application/json


###  create
POST http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNTc0NTN9.TMQY5EZPnjKn0q5k2RfEoinvYhQFylxBl-1FeSw6ALs
Content-Type: application/json

{
  "name": "user 2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}